### PR TITLE
Add id attribute prop to editor component

### PR DESCRIPTION
**Pull request by Shubham-p-patil**
I was trying to access the editor using `document.getElementById()` but there was no attribute id given to the editor due to which I was always getting a `null` value. I have therefore added an attribute id which will give the access of the Monaco editor as element from HTML document.

### CODE REVIEW

**Comment by suren-atoyan** [comment]
Hello @Shubham-p-patil. First, thank you for your support, but I don't think there can be an argument to do so. First of all, it's unusual for react component to have an id. As the first aim of react component is a reusable combination of layout and logic, so, from this point of view, usually, there is no id on react components, otherwise, you have to manage the uniqueness of id throughout the document. The second is the need to have an access to the editor component container but in any case if you really need it you can get it by `document.querySelector('....')` with the wrapper class name. I mean to say, where you add the id, there is a `className`, so, what's the reason for not using the `className`?

**Comment by Shubham-p-patil** [comment]
Hello @suren-atoyan. Thank you for your response. Yes, definitely we can get it through  `className` by using `document.querySelector('...')` but if we have more than one editor component on the page then I won't be able to apply any changes to one of them without applying those changes to all the editor components present on that page. By using a unique id we will be able to access that one component and manipulate that single component only. Furthermore, this might also help in using react portals.

**Comment by suren-atoyan** [comment]
So what's the problem to use the unique className? When use use id prop, you have to provide a unique id to that "unique" component, so provide a unique className instead.

**Comment by Shubham-p-patil** [comment]
Yes, you can definitely do that no problem with it but the general trend in HTML is to have an id prop for this as multiple HTML elements can have the same className while an id name must only be used by one HTML elements. That is why i suggested adding id as a prop.

**Comment by suren-atoyan** [comment]
There is a plan to add `containerProps` that is going to be directly passed to `MonacoContainer` (and the `wrapperClassName` will be removed). So, one can pass an id or whatever he/she wants. But for now, id prop can't be separately added.

The PR won't be merged, I would kindly ask you to open an issue about `containerProps` that I can keep you up to date (I hope It will be done the next week). Otherwise, I'll keep this open to be able to inform you about the new version.

**Pull request closed without merging**
