### PR TITLE
Avoiding state change while unmounted

### LINKED ISSUE #52: React state update on unmounted component
If you quickly render and kill a component with monaco-react in it the following error happens :
```
backend.js:6 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in Editor
    in Editor (created by SizedDiv)
    in div (created by SizedDiv)
    in SizedDiv (created by SrcEditor)
    in SrcEditor (created by WegasScriptEditor)
    in WegasScriptEditor (created by ExpressionEditor)
    in div (created by ExpressionEditor)
    in div (created by ExpressionEditor)
    in ExpressionEditor (created by Labeled)
    in Labeled (created by StatementView)
    in div (created by CommonViewContainer)
    in CommonViewContainer (created by StatementView)
    in StatementView (created by j)
    in j (created by r)
    in r (created by n)
    in n (created by Context.Consumer)
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in Unknown (created by n)
    in n (created by n)
    in n (created by r)
    in fieldset (created by ObjectView)
    in div (created by CommonViewContainer)
    in CommonViewContainer (created by ObjectView)
    in ObjectView (created by j)
    in j (created by r)
    in r (created by n)
    in n (created by Context.Consumer)
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in Unknown (created by n)
    in n (created by n)
    in n
    in div (created by ArrayItem)
    in div (created by ArrayItem)
    in ArrayItem (created by Labeled)
r @ backend.js:6
warningWithoutStack @ react-dom.development.js:545
warnAboutUpdateOnUnmountedFiberInDEV @ react-dom.development.js:23177
scheduleUpdateOnFiber @ react-dom.development.js:21394
dispatchAction @ react-dom.development.js:15816
(anonymous) @ Editor.js:67
Promise.then (async)
(anonymous) @ Editor.js:66
commitHookEffectList @ react-dom.development.js:19986
commitPassiveHookEffects @ react-dom.development.js:20016
callCallback @ react-dom.development.js:347
invokeGuardedCallbackDev @ react-dom.development.js:397
invokeGuardedCallback @ react-dom.development.js:454
flushPassiveEffectsImpl @ react-dom.development.js:22868
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11305
flushPassiveEffects @ react-dom.development.js:22841
renderRoot @ react-dom.development.js:21801
runRootCallback @ react-dom.development.js:21554
(anonymous) @ react-dom.development.js:11353
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11305
flushSyncCallbackQueueImpl @ react-dom.development.js:11349
flushSyncCallbackQueue @ react-dom.development.js:11338
discreteUpdates$1 @ react-dom.development.js:21677
discreteUpdates @ react-dom.development.js:2359
dispatchDiscreteEvent @ react-dom.development.js:5979
```
The same error is happening with the diffEditor.

I'll soon make a pull request to correct this.

### PR DESCRIPTION
**Pull request by IamFonky**
fixes #52

### CODE REVIEW

**Comment by suren-atoyan** [comment]
There are some objections and notes regarding those changes:

1) the definition of `mountedRef` and other stuff shouldn't be in `editor.js` or `diffEditor.js`. First of all, you are repeating yourself, and second, it's out of the main logic of `editor` and `diffEditor`; it should be a complete solution defined in another place (let's say in `utils/hooks`) and used in `editor.js` or diffEditor.js as a utility.

2) I would like to see a hook, which is called something like `useUnmount` (`const { isUnmounted } = useUnmount()`) and we can use `isUnmounted` as a checking target, instead of `isMounted`, because we are interested in being unmounted not !mounted. There are no differences from a technical point of view and there is no even significant difference from the semantic point of view, but it's more clear.

3) and about the ordering of "cancelation". You wrote

`.then(monaco => (monacoRef.current = monaco) && !isUnmounted && setIsMonacoMounting(false))`

we need to do "nothing" right after isUnmounted is true, hence, we can move forward that very check. It should be something like this:

`.then(monaco => !isUnmounted && ((monacoRef.current = monaco) && setIsMonacoMounting(false)))`

**Comment by IamFonky** [comment]
Thanks for your last review :+1: 
Sorry for making so long but it was a very busy week for me.
What do you think this way to do it? I tried to make as few changes as possible.

**Comment by suren-atoyan** [comment]
Hello @IamFonky,

I've reviewed your changes. And there is something I don't like it. (don't get me wrong please, we have to solve it by the best way only).

So, the first complaint is about isMounted inside useMounted. I assume it's not sensible because usually, we expect that the function provided to useMounted should be called when a component has already mounted; in that case except us nobody will understand the meaning of isMounted inside useMounted. At least, it should be something like stillMounted to make sense from a semantics point of view. But in any case, the concept is wrong.

Let me think a little bit, I'll suggest a better way.

**Comment by suren-atoyan** [comment]
Here we are.

There is a [post](https://reactjs.org/blog/2015/12/16/ismounted-antipattern.html) in reactjs.org (from 2015) about `isMounted`, and how it's an anti-pattern. You also can read about it in [Reddit](https://www.reddit.com/r/reactjs/comments/cqfo3r/is_ismounted_an_antipattern/) and in [stack-overflow](https://stackoverflow.com/questions/54327076/why-is-the-cancelledpromise-pattern-considered-better-than-the-ismounted-anti).

To be short - the `monaco.init()` returns a promise, it should return a cancelable promise instead, and that very cancelable promise should be canceled in `willUnmount` (in our case in `useEffect`).

So, it should be something like this:

Screen Shot 2020-02-06 at 18 45 44

**Comment by suren-atoyan** [comment]
The implementation of this gonna be quite complex, so, let me do it, I'll share the results in the discussion of the issue; before that, you can close the PR.

**Comment by IamFonky** [comment]
All right.
Nice research job and thank you for your help!

**Comment by IamFonky** [comment]
A better way with cancelable promise was found.

**Pull request closed without merging**
